config/routes.rb
SocialAggregator::Application.routes.draw do
  get "home/index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  unauthenticated :user do
    devise_scope :user do 
      get "/" => 'devise/registrations#new'
    end
  end
  
  authenticate :user do
    root :to => 'social_inbox_feeds#index'
  end
  resources :social_inbox_feeds do
    collection do
      get :filter_feeds
    end
  end
  

  

end

app/models/facebook_api.rb
class FacebookApi
  class << self
    def graph(facebook_oauth_token)
      Koala::Facebook::API.new(facebook_oauth_token)
    end

    def home_feeds(start_time, access_token)
      graph(access_token).get_connections("me", "home", {:since => start_time + 1, :until => Time.now.to_i})
    end

    def feed(access_token, feed_id)
      graph(access_token).get_object(feed_id)
    end
    
    def user_details(access_token)
      graph(access_token).get_object("me")
    end
  end
end

app/models/facebook_profile.rb
class FacebookProfile < ActiveRecord::Base
  belongs_to :social

  def authorized?
    facebook_oauth_token.present?
  end

  def find_for_oauth(auth)
    if !((facebook_oauth_token == auth.credentials["token"]) && (facebook_uid == auth.uid))      
      self.update_attributes!(facebook_oauth_token: auth.credentials["token"], facebook_uid: auth.uid)
    end
    Resque.enqueue(FacebookProfileDetailsJob, social.id)
  end
end

app/models/linkedin_profile.rb
class LinkedinProfile < ActiveRecord::Base
  belongs_to :social

  def authorized?
    linkedin_oauth_token.present?
  end
  
  def find_for_oauth(auth)
    if !((linkedin_oauth_token == auth.credentials["token"]) &&
      (linkedin_uid == auth.uid) && (linkedin_oauth_secret_token == auth.credentials["secret"]))
      self.update_attributes(linkedin_oauth_token: auth.credentials["token"],
      linkedin_uid: auth.uid, linkedin_oauth_secret_token: auth.credentials["secret"])
    end
  end
  
  def client
    client = LinkedIn::Client.new("ni01x8rzbbga", "FyxHaqIlXoF6c4d5")
    client.authorize_from_access(linkedin_oauth_token, linkedin_oauth_secret_token)
    client
  end
end

app/models/social.rb
class Social < ActiveRecord::Base

  has_one     :facebook_profile, autosave: true
  has_one     :twitter_profile, autosave: true
  has_one     :linkedin_profile, autosave: true
  has_many    :social_inbox_feeds
  belongs_to  :user 
end

app/models/social_inbox_feed.rb
class SocialInboxFeed < ActiveRecord::Base
  belongs_to :social

  module INBOXTYPE
    FACEBOOK = "facebook"
    USERTIMELINE = "home_timeline"
    LINKEDIN = "linkedin"
  end
  
  def self.parse(feed, social)
    social_inbox_feed =  SocialInboxFeed.find_or_create_by({feed_id: feed["id"]})
    social_inbox_feed.update_attributes({message: feed["message"], story: feed["story"],
      photo: feed["picture"], link: feed["link"], created_time: Time.parse(feed["created_time"]),
      updated_time: Time.parse(feed["updated_time"]), user_name: feed["from"]["name"], social_id: social.id, 
      inbox_type: INBOXTYPE::FACEBOOK, user_id: feed["from"]["id"]})
      puts "Social Inbox Feed: #{social_inbox_feed.inspect}"
    social_inbox_feed
  end  
  
  def self.search(search)
    if search
      find(:all, :conditions => ['user_name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

  def facebook?
    self["inbox_type"] == INBOXTYPE::FACEBOOK
  end

  def twitter?
    self["inbox_type"] == INBOXTYPE::USERTIMELINE
  end

  def linkedin?
    self["inbox_type"] == INBOXTYPE::LINKEDIN
  end
  
  def self.parse_tweet(tweet, inbox_type, social)
    social_inbox_feed =  SocialInboxFeed.find_or_create_by({tweet_id: tweet.id})

    social_inbox_feed.update_attributes({message: tweet.text, created_time: tweet.created_at,
     updated_time: tweet.created_at, user_id: tweet.user.id, user_name: tweet.user.name,
     inbox_type: inbox_type, social_id: social.id})
    social_inbox_feed
  end
end

app/models/twitter_profile.rb
class TwitterProfile < ActiveRecord::Base
  belongs_to :social

  def authorized?
    twitter_oauth_token.present?
  end
  
  def find_for_oauth(auth)
    if !((twitter_oauth_token == auth.credentials["token"]) &&
      (twitter_uid == auth.uid) && (twitter_oauth_secret_token == auth.credentials["secret"]))
      self.update_attributes(twitter_oauth_token: auth.credentials["token"],
      twitter_uid: auth.uid, twitter_oauth_secret_token: auth.credentials["secret"])
    end
    create_twitter
  end
  
  def create_twitter
    Resque.enqueue(TwitterDetailsJob, self.id)
  end
  
  def client
    Twitter::Client.new(:oauth_token => twitter_oauth_token, :oauth_token_secret => twitter_oauth_secret_token)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise    :database_authenticatable, :registerable,
            :recoverable, :rememberable, :trackable, :validatable, :omniauthable
         
  has_one   :social
  
  def check_social_profile?(profile)
    profile.present? && profile.authorized?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/social_inbox_feeds_controller.rb
require 'will_paginate/array'
class SocialInboxFeedsController < ApplicationController  
  def index
    @feeds = current_user.social.social_inbox_feeds.search(params[:search]).paginate(:page => params[:page], :per_page => 10) if current_user.social.present?
    respond_to :html, :js
  end
  
  def filter_feeds
    @feeds = current_user.social.social_inbox_feeds.where(inbox_type: params[:inbox_type]).search(params[:search]).paginate(:page => params[:page], :per_page => 10)
    respond_to :html, :js  
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_filter :social_profiles

  def facebook
    current_user.social.facebook_profile.find_for_oauth(request.env["omniauth.auth"])
    redirect_to root_url
  end

  def twitter
    current_user.social.twitter_profile.find_for_oauth(request.env["omniauth.auth"])
    redirect_to root_url
  end

  def linkedin
    current_user.social.linkedin_profile.find_for_oauth(request.env["omniauth.auth"])
    redirect_to root_url
  end
  
  private
  def social_profiles
    unless current_user.social.present?
      @social = current_user.build_social
      @social.save
      @fp = @social.build_facebook_profile
      @fp.save
      @tp = @social.build_twitter_profile
      @tp.save
      @linkedin = @social.build_linkedin_profile
      @linkedin.save
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/social_inbox_feeds_helper.rb
module SocialInboxFeedsHelper
end

app/views/home/index.html.haml
%section#main_content
  - if user_signed_in?
    %article#welcome
      %p
        You are in the app :)
      %p
        = link_to "Edit Profile", edit_user_registration_path(current_user)
      %p
        = link_to "Sign out", destroy_user_session_path, method: :delete
    %article#social-section
      = render partial: "social_block"
    .clear
    %article#social-search-part
      %div.filter-part-block
        %span.span1
          Filter By: 
        %span
          = link_to image_tag(asset_path("facebook-icon.png")), social_inbox_feed_filter_feeds_path, class: "filter-part span1", "data-inboxtype" => SocialInboxFeed::INBOXTYPE::FACEBOOK
          = link_to image_tag(asset_path("twitter-icon.png")), social_inbox_feed_filter_feeds_path, class: "filter-part span1", "data-inboxtype" => SocialInboxFeed::INBOXTYPE::USERTIMELINE
          = link_to image_tag(asset_path("linkedin-icon.png")), social_inbox_feed_filter_feeds_path, class: "filter-part span1", "data-inboxtype" => SocialInboxFeed::INBOXTYPE::LINKEDIN
      .clear  
      %div.search-part
        = form_tag social_inbox_feeds_path, :method => 'get' do
          %p
            = text_field_tag :search, params[:search]
            = submit_tag "Search", :name => nil
    .clear
    %article#social-feeds-inbox
      = will_paginate @feeds
      = render partial: "social_inbox_feeds"
    .clear
    = link_to "Show More", "#", class: "btn btn-primary show-more"
  - else
    %article#sign_up
      %h1
        Social Aggregator
      %h1
        Sign Up for Free
      %p
        = link_to "Register", new_user_registration_path, class: "btn btn-primary"
      %p.sign_in
        %span
          = link_to "Sign In", new_user_session_path, class: "sign_in btn btn-primary"

app/views/layouts/application.html.haml
!!! Strict
%html
  %head
    %title= "Social Aggregator"
    = stylesheet_link_tag  "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body.span12
    - flash.each do |name, msg|
      %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
        %a.close{"data-dismiss" => "alert"} ×
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
    = yield

app/views/social_inbox_feeds/_feed_block.html.haml
%span.span6
  %h3
    From 
    %span
      = feed.user_name
  .clear
  %p
    = feed.message

app/views/social_inbox_feeds/_social_block.html.haml
%section.social_block
  %header.social_buttons
    - if current_user.social.present? && current_user.check_social_profile?(current_user.social.facebook_profile)
      .connected-block
        %span.span1
          = image_tag(asset_path("facebook-icon.png"))
        %span.span2
          = current_user.social.facebook_profile.name
          %br
          Authenticated
    - else
      = link_to(image_tag(asset_path("facebook.png")), omniauth_authorize_path(current_user, :facebook), class: "span3 no-margin-left")
    - if current_user.social.present? && current_user.check_social_profile?(current_user.social.twitter_profile)
      .connected-block
        %span.span1
          = image_tag(asset_path("twitter-icon.png"))
        %span.span2
          = current_user.social.twitter_profile.name
          %br
          Authenticated
    - else
      = link_to(image_tag(asset_path("twitter.png")), omniauth_authorize_path(current_user, :twitter), class: "span3 no-margin-left")
    - if current_user.social.present? && current_user.check_social_profile?(current_user.social.linkedin_profile)
      .connected-block
        %span.span1
          = image_tag(asset_path("linkedin-icon.png"))
        %span.span2
          = current_user.social.linkedin_profile.name
          %br
          Authenticated
    - else
      = link_to(image_tag(asset_path("linkedin.png")), omniauth_authorize_path(current_user, :linkedin), class: "span3 no-margin-left")

app/views/social_inbox_feeds/_social_inbox_feeds.html.haml
- if @feeds.present?
  %ul.span10.feeds_list
    - @feeds.each do |feed|
      %li
        - if feed.facebook?
          %span.span2
            = image_tag(asset_path("facebook-icon.png"))
          = render partial: "feed_block", locals: {feed: feed}
        - if feed.twitter?
          %span.span2
            = image_tag(asset_path("twitter-icon.png"))
          = render partial: "feed_block", locals: {feed: feed}
        - if feed.linkedin?
          %span.span2
            = image_tag(asset_path("twitter-icon.png"))
          = render partial: "feed_block", locals: {feed: feed}
      .clear
- else
  %p
    There are no more feeds

app/views/social_inbox_feeds/filter_feeds.js.erb
$("article#social-feeds-inbox").empty();
$("article#social-feeds-inbox").html("<%= escape_javascript(render('social_inbox_feeds')) %>")

app/views/social_inbox_feeds/index.html.haml
%section#main_content
  - if user_signed_in?
    %article#welcome
      %p
        You are in the app :)
      %p
        = link_to "Edit Profile", edit_user_registration_path(current_user)
      %p
        = link_to "Sign out", destroy_user_session_path, method: :delete
    %article#social-section
      = render partial: "social_block"
    .clear
    - if current_user.social.present?
      %article#social-search-part
        %div.filter-part-block
          %span.span1
            Filter By: 
          %span
            = link_to image_tag(asset_path("facebook-icon.png")), filter_feeds_social_inbox_feeds_path, class: "filter-part span1", "data-inboxtype" => SocialInboxFeed::INBOXTYPE::FACEBOOK
            = link_to image_tag(asset_path("twitter-icon.png")), filter_feeds_social_inbox_feeds_path, class: "filter-part span1", "data-inboxtype" => SocialInboxFeed::INBOXTYPE::USERTIMELINE
            = link_to image_tag(asset_path("linkedin-icon.png")), filter_feeds_social_inbox_feeds_path, class: "filter-part span1", "data-inboxtype" => SocialInboxFeed::INBOXTYPE::LINKEDIN
        .clear  
        %div.search-part
          = form_tag social_inbox_feeds_path, :method => 'get' do
            %p
              = text_field_tag :search, params[:search]
              = submit_tag "Search", :name => nil
      .clear
      %article#social-feeds-inbox
        = will_paginate @feeds
        = render partial: "social_inbox_feeds"
      .clear
      = link_to "Show More", "#", class: "btn btn-primary show-more"
  - else
    %article#sign_up
      %h1
        Social Aggregator
      %h1
        Sign Up for Free
      %p
        = link_to "Register", new_user_registration_path, class: "btn btn-primary"
      %p.sign_in
        %span
          = link_to "Sign In", new_user_session_path, class: "sign_in btn btn-primary"

app/views/social_inbox_feeds/index.js.erb
if(<%=@feeds.present? %>){
  $("article#social-feeds-inbox").append("<%= escape_javascript(render('social_inbox_feeds')) %>")
}
else {
  $(".show-more").hide();
}